version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  php-fpm:
    build: docker/php
    container_name: php-fpm
    volumes:
      - .:/var/www
    environment:
      - PROJECT_DIR=$PROJECT_DIR
      - PROJECT_NAME=$PROJECT_NAME
      - PROJECT_PATH=$PWD
    ports:
      - 9000:9000

  nginx:
    build:
      context: docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx:rw
    depends_on:
      - php-fpm
    ports:
      - "81:80"

volumes:
  mongodb_data_container:
