version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  php:
    build: .docker/php
    container_name: php7_fpm
    volumes:
      - .:$PWD
    environment:
      - PROJECT_DIR=$PROJECT_DIR
      - PROJECT_NAME=$PROJECT_NAME
      - PROJECT_PATH=$PWD

volumes:
  mongodb_data_container:
